version: 2

models:
  - name: movement
    description: Table containing the movement of the vehicles.
    columns:
      - name: fahrtnummer
        description: The unique number to identify journey of a bus.
        tests:
          - not_null
